# Generated by Django 5.2.6 on 2025-09-20 05:47

import recursos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=recursos.models.get_recursos_s3_file_path)),
            ],
        ),
    ]
