# Generated by Django 5.2.7 on 2025-10-15 00:35

import django.db.models.deletion
import recursos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('tipo_acceso', models.CharField(choices=[('publico', 'Público'), ('privado', 'Privado')], default='privado', max_length=10)),
                ('file', models.FileField(upload_to=recursos.models.get_recursos_s3_file_path)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='usuarios.instituciones')),
                ('usuario_subio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos_subidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
