# Generated by Django 5.2.7 on 2025-10-27 19:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FillingStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('number', models.PositiveIntegerField(help_text='Número de llenado/etapa')),
                ('people', models.CharField(help_text='Personas que hicieron el llenado', max_length=255)),
                ('material_type', models.CharField(choices=[('bovino', 'Desechos bovinos'), ('porcino', 'Desechos porcinos'), ('vegetal', 'Residuos vegetales')], max_length=20)),
                ('material_amount_kg', models.FloatField()),
                ('material_humidity_pct', models.FloatField()),
                ('added_water_m3', models.FloatField(default=0.0)),
                ('temperature_c', models.FloatField(default=35.0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('pressure_hpa', models.FloatField(blank=True, null=True)),
                ('biol_flow', models.FloatField(blank=True, help_text='Caudal biol (unidades del sensor)', null=True)),
                ('gas_flow', models.FloatField(blank=True, help_text='Caudal gas (unidades del sensor)', null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='dashboard.fillingstage')),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='dashboard_s_timesta_64d695_idx'), models.Index(fields=['stage', 'timestamp'], name='dashboard_s_stage_i_f4d7f3_idx')],
            },
        ),
    ]
