# Generated by Django 5.2.7 on 2025-10-28 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('normal', 'Reporte regular'), ('final', 'Reporte final de producción')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('inferences', models.TextField(blank=True, null=True)),
                ('production_estimated', models.FloatField(blank=True, null=True)),
                ('production_real', models.FloatField(blank=True, null=True)),
                ('file_pdf', models.FileField(blank=True, null=True, upload_to='reports/pdf/')),
                ('file_excel', models.FileField(blank=True, null=True, upload_to='reports/excel/')),
                ('file_csv', models.FileField(blank=True, null=True, upload_to='reports/csv/')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='dashboard.fillingstage')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
