# Generated by Django 5.2.7 on 2025-11-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActuatorCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.CharField(help_text='electrovalvula|piston|otro', max_length=50)),
                ('target', models.CharField(help_text='identificador del dispositivo', max_length=100)),
                ('action', models.CharField(choices=[('OPEN', 'Abrir'), ('CLOSE', 'Cerrar'), ('SET', 'Establecer valor')], max_length=10)),
                ('value', models.FloatField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('SENT', 'Enviado'), ('ERROR', 'Error')], default='PENDING', max_length=10)),
                ('response_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARN', 'Advertencia'), ('CRIT', 'Crítico')], max_length=5)),
                ('message', models.CharField(max_length=255)),
                ('details', models.JSONField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CalibrationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sensor_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='calibrations/')),
            ],
        ),
    ]
