# Generated by Django 5.2.3 on 2025-09-19 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Calculation', max_length=100)),
                ('retention_time', models.FloatField(default=30, help_text='Hydraulic Retention Time (days)')),
                ('water_ratio', models.FloatField(default=1.0, help_text='Water:Feedstock ratio (e.g., 1.0 for 1:1)')),
                ('temperature', models.FloatField(default=35.0, help_text='Digester temperature (°C)')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('total_biogas', models.FloatField(blank=True, null=True)),
                ('total_slurry', models.FloatField(blank=True, null=True)),
                ('required_volume', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedstock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_solids', models.FloatField(help_text='TS (%)')),
                ('volatile_solids', models.FloatField(help_text='VS (% of TS)')),
                ('cn_ratio', models.FloatField(blank=True, help_text='C:N Ratio (optional)', null=True)),
                ('biogas_yield', models.FloatField(blank=True, help_text='m³ Biogas per kg VS', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_amount', models.FloatField(help_text='kg/day')),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='biocalculadora.calculation')),
                ('feedstock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biocalculadora.feedstock')),
            ],
            options={
                'unique_together': {('calculation', 'feedstock')},
            },
        ),
    ]
