# Generated by Django 5.2.7 on 2025-11-01 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AprobarUsuarios', models.BooleanField(default=False)),
                ('VerReportes', models.BooleanField(default=False)),
                ('GenerarReportes', models.BooleanField(default=False)),
                ('VerDashboard', models.BooleanField(default=False)),
                ('VerInventario', models.BooleanField(default=False)),
                ('ModificarInventario', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprobado', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
                ('permisos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.permisos')),
            ],
        ),
    ]
