# Generated by Django 5.2.7 on 2025-11-04 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_perfil_permisos'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('COLAB', 'Colaborador'), ('VISIT', 'Visitante')], default='VISIT', max_length=10),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='permisos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.permisos'),
        ),
    ]
